### ISSUE TITLE
tree-diff-0.4 failed to build with semialign-1.3.1.1 in stackage nightly

### ISSUE THREAD

**Issue by juhp** [haskellari/these#216]
```
       Building library for tree-diff-0.4... 
       [ 1 of 10] Compiling Data.TreeDiff.List
       [ 2 of 10] Compiling Data.TreeDiff.OMap
       /home/curators/work/unpack-dir/unpacked/tree-diff-0.4-f5c15a2dccb766a166c7e56c30e580a0044de5ab8c7509f20f40f9da5e13dd56/src/Da
ta/TreeDiff/OMap.hs:152:10: error: [GHC-39999]      
           • No instance for ‘semialign-1.3.1.1:Data.Semialign.Internal.Zip                                                         
                                (OMap k)’                      
               arising from the superclasses of an instance declaration                                                             
           • In the instance declaration for ‘Unzip (OMap k)’
           |
       152 | instance Unzip (OMap k) where
           |          ^^^^^^^^^^^^^^
        
       [10 of 10] Compiling Data.TreeDiff.Tree
```

Is this related with the semialign-1.4 release?

**Comment by phadej** [comment]
Yes, it's related. I see. I'll fix this ASAP.

**Comment by phadej** [comment]
This is however issue in `tree-diff`, not `semialign`. So I'm closing this.

**Comment by phadej** [comment]
- made revisions: tree-diff-0.3.5 and tree-diff-0.4 require semialign >=1.4
- tree-diff-0.4.1 works with both semialign-1.4 and semialign-1.3

So if people want can upgrade only one major at the time, they can do it.

- tree-diff-0.3.* (<0.3.5) -> tree-diff-0.4.1 can keep semialign-1.3 for time being
 - tree-diff-0.3.* -> tree-diff-0.3.5 can be used to upgrade semialign keeping tree-diff in its major.
