### ISSUE TITLE
Can't compile with GHC 9.2.1

### ISSUE THREAD

**Issue by LeventErkok** [haskellari/these#169]
```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.2.1
```

```
Configuring library for semialign-1.2..
Preprocessing library for semialign-1.2..
Building library for semialign-1.2..
[1 of 6] Compiling Data.Semialign.Internal

src/Data/Semialign/Internal.hs:31:43: error:
    Module ‘Data.Semigroup’ does not export ‘Option(..)’
   |
31 | import Data.Semigroup                    (Option (..), Semigroup (..))
   |                                           ^^^^^^^^^^^
cabal: Failed to build semialign-1.2. See the build log above for details.
```

**Comment by phadej** [comment]
There are already fixes in flight in #168 and #167.

**Comment by LeventErkok** [comment]
Duplicate indeed. Closing.

**Comment by LeventErkok** [comment]
@phadej Looks like all the bits are ready? Will there be a Hackage release soon?
